"""Smart Travel Assistant shared contracts (baseline v1)."""

from sta_contracts import enums, geo, models
from sta_contracts.enums import CONTRACT_VERSION

# Models exported to JSON Schema / TypeScript, in a stable order.
EXPORTED_MODELS: list[type[models.ContractModel]] = [
    models.LocationRef,
    models.TravelPreference,
    models.TravelRequest,
    models.SourceProvenance,
    models.DataConflict,
    models.DataQuality,
    models.WeatherForecastPoint,
    models.TransportStatus,
    models.DisasterEvent,
    models.RouteSegment,
    models.RouteExposure,
    models.RouteCandidate,
    models.TravelWindow,
    models.QualitySummary,
    models.ConflictSummary,
    models.IntegratedTravelContext,
    models.ModelRef,
    models.SafetyOverride,
    models.RiskAssessment,
    models.RetrievedEvidence,
    models.EvidencePackage,
    models.VersionInfo,
    models.DecisionValidation,
    models.DecisionResult,
    models.OfficialContact,
    models.AlertItem,
    models.Freshness,
    models.EmergencyInstruction,
    models.RecommendationResponse,
    models.RunRef,
    models.RunProgressEvent,
    models.RunState,
    models.ConsentRecord,
    models.UserProfile,
    models.EmergencyContactPerson,
    models.EmergencyProfile,
    models.Trip,
    models.FeedbackEvent,
    models.AlertSubscription,
    models.Conversation,
    models.ConversationMessage,
    models.TimeWindow,
    models.ContextQuery,
    models.ProviderHealth,
    models.ExternalContext,
    models.SnapshotCreateRequest,
    models.EvidencePackageRequest,
    models.DecisionRequest,
    models.RecommendationCreateRequest,
    models.AgentRunRequest,
]

__all__ = ["CONTRACT_VERSION", "EXPORTED_MODELS", "enums", "geo", "models"]
