"""Shared enums (00_API_AND_DATA_CONTRACTS §2). Uppercase on the wire; unknown provider values map to UNKNOWN."""

from __future__ import annotations

from enum import StrEnum

CONTRACT_VERSION = "1.0.0"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    UNKNOWN = "UNKNOWN"


class ActionCode(StrEnum):
    NORMAL = "NORMAL"
    CHANGE_ROUTE = "CHANGE_ROUTE"
    DELAY = "DELAY"
    AVOID = "AVOID"


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    NEEDS_INPUT = "NEEDS_INPUT"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TravelMode(StrEnum):
    FLIGHT = "FLIGHT"
    TRAIN = "TRAIN"
    BUS = "BUS"
    CAR = "CAR"
    WALK = "WALK"
    BICYCLE = "BICYCLE"
    MULTIMODAL = "MULTIMODAL"


class DataStatus(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    UNAVAILABLE = "UNAVAILABLE"
    CONFLICTING = "CONFLICTING"
    PARTIAL = "PARTIAL"


class Severity(StrEnum):
    INFO = "INFO"
    MINOR = "MINOR"
    MODERATE = "MODERATE"
    SEVERE = "SEVERE"
    EXTREME = "EXTREME"
    UNKNOWN = "UNKNOWN"


SEVERITY_RANK: dict[Severity, int] = {
    Severity.UNKNOWN: 0,
    Severity.INFO: 1,
    Severity.MINOR: 2,
    Severity.MODERATE: 3,
    Severity.SEVERE: 4,
    Severity.EXTREME: 5,
}


class SourceAuthority(StrEnum):
    OFFICIAL = "OFFICIAL"
    INTERGOVERNMENTAL = "INTERGOVERNMENTAL"
    LICENSED_PROVIDER = "LICENSED_PROVIDER"
    COMMUNITY = "COMMUNITY"
    UNKNOWN = "UNKNOWN"


AUTHORITY_RANK: dict[SourceAuthority, int] = {
    SourceAuthority.UNKNOWN: 0,
    SourceAuthority.COMMUNITY: 1,
    SourceAuthority.LICENSED_PROVIDER: 2,
    SourceAuthority.INTERGOVERNMENTAL: 3,
    SourceAuthority.OFFICIAL: 4,
}


class FeedbackCategory(StrEnum):
    HELPFUL = "HELPFUL"
    INCORRECT = "INCORRECT"
    STALE = "STALE"
    UNSAFE = "UNSAFE"
    ROUTE_ISSUE = "ROUTE_ISSUE"
    SOURCE_ISSUE = "SOURCE_ISSUE"
    OTHER = "OTHER"


class ConsentType(StrEnum):
    LOCATION_ONCE = "LOCATION_ONCE"
    LOCATION_LIVE = "LOCATION_LIVE"
    ALERT_NOTIFICATION = "ALERT_NOTIFICATION"
    ANALYTICS = "ANALYTICS"
    EMERGENCY_PROFILE = "EMERGENCY_PROFILE"


class DeliveryChannel(StrEnum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    SMS = "SMS"
    PUSH = "PUSH"


class ProviderKind(StrEnum):
    GEOCODING = "GEOCODING"
    WEATHER = "WEATHER"
    ROUTE = "ROUTE"
    FLIGHT = "FLIGHT"
    TRANSIT = "TRANSIT"
    DISASTER = "DISASTER"
    EMERGENCY_DIRECTORY = "EMERGENCY_DIRECTORY"
    PLACES = "PLACES"


class QualityFlag(StrEnum):
    MISSING = "MISSING"
    STALE = "STALE"
    CONFLICTING = "CONFLICTING"
    INFERRED = "INFERRED"
    INCOMPLETE = "INCOMPLETE"
    OUTSIDE_COVERAGE = "OUTSIDE_COVERAGE"


class TransportServiceStatus(StrEnum):
    ON_TIME = "ON_TIME"
    DELAYED = "DELAYED"
    CANCELLED = "CANCELLED"
    DISRUPTED = "DISRUPTED"
    UNKNOWN = "UNKNOWN"


class DisasterEventType(StrEnum):
    EARTHQUAKE = "EARTHQUAKE"
    CYCLONE = "CYCLONE"
    STORM = "STORM"
    FLOOD = "FLOOD"
    WILDFIRE = "WILDFIRE"
    VOLCANO = "VOLCANO"
    LANDSLIDE = "LANDSLIDE"
    EXTREME_TEMPERATURE = "EXTREME_TEMPERATURE"
    HEALTH = "HEALTH"
    TRANSPORT_CLOSURE = "TRANSPORT_CLOSURE"
    OTHER = "OTHER"


class RouteLabel(StrEnum):
    ORIGINAL = "ORIGINAL"
    RECOMMENDED = "RECOMMENDED"
    FASTEST = "FASTEST"
    LOWEST_RISK = "LOWEST_RISK"
    ALTERNATIVE = "ALTERNATIVE"


class RunStage(StrEnum):
    VALIDATING = "VALIDATING"
    FETCHING_EXTERNAL_DATA = "FETCHING_EXTERNAL_DATA"
    INTEGRATING_DATA = "INTEGRATING_DATA"
    ASSESSING_RISK = "ASSESSING_RISK"
    RETRIEVING_GUIDANCE = "RETRIEVING_GUIDANCE"
    EVALUATING_ROUTES = "EVALUATING_ROUTES"
    MAKING_DECISION = "MAKING_DECISION"
    EXPLAINING = "EXPLAINING"
    FORMATTING_RESPONSE = "FORMATTING_RESPONSE"


class QualityGate(StrEnum):
    PASS = "PASS"
    DEGRADED = "DEGRADED"
    BLOCK = "BLOCK"


class Intent(StrEnum):
    PLAN_TRIP = "PLAN_TRIP"
    CHECK_SAFETY = "CHECK_SAFETY"
    ASK_INFORMATION = "ASK_INFORMATION"
    FOLLOW_UP = "FOLLOW_UP"
    EMERGENCY = "EMERGENCY"


class ReasonCode(StrEnum):
    """Controlled vocabulary for risk/decision reasons (LLM may only paraphrase these)."""

    SEVERE_WEATHER_CORRIDOR = "SEVERE_WEATHER_CORRIDOR"
    HEAVY_PRECIPITATION = "HEAVY_PRECIPITATION"
    HIGH_WIND = "HIGH_WIND"
    LOW_VISIBILITY = "LOW_VISIBILITY"
    EXTREME_TEMPERATURE = "EXTREME_TEMPERATURE"
    EARTHQUAKE_NEAR_CORRIDOR = "EARTHQUAKE_NEAR_CORRIDOR"
    ACTIVE_DISASTER_EVENT = "ACTIVE_DISASTER_EVENT"
    OFFICIAL_ALERT_ACTIVE = "OFFICIAL_ALERT_ACTIVE"
    OFFICIAL_CLOSURE = "OFFICIAL_CLOSURE"
    TRANSPORT_DISRUPTION = "TRANSPORT_DISRUPTION"
    TRANSPORT_DELAY = "TRANSPORT_DELAY"
    SAFER_ROUTE_AVAILABLE = "SAFER_ROUTE_AVAILABLE"
    NO_SAFER_ROUTE = "NO_SAFER_ROUTE"
    RISK_DECREASES_LATER = "RISK_DECREASES_LATER"
    LOW_DATA_COVERAGE = "LOW_DATA_COVERAGE"
    STALE_DATA = "STALE_DATA"
    CONFLICTING_SOURCES = "CONFLICTING_SOURCES"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    NO_RELIABLE_KNOWLEDGE_EVIDENCE = "NO_RELIABLE_KNOWLEDGE_EVIDENCE"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    CONDITIONS_NORMAL = "CONDITIONS_NORMAL"
